<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('brands')->insert([
            
            // ========================================
            // FAST FASHION (Roupas Acessíveis)
            // ========================================
            
            [
                'name' => 'Shein',
                'slug' => 'shein',
                'description' => 'Marca chinesa de fast fashion com peças modernas e acessíveis. Tendências globais a preços competitivos.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'China',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 1,
                'meta_title' => 'Shein Angola - Moda Fast Fashion | Teu Estilo',
                'meta_description' => 'Produtos Shein em Angola: roupas modernas, acessórios e cosméticos a preços acessíveis. Tendências globais em Luanda. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Zara',
                'slug' => 'zara',
                'description' => 'Marca espanhola de moda conhecida por designs contemporâneos e qualidade superior. Estilo europeu sofisticado.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Espanha',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 2,
                'meta_title' => 'Zara Angola - Moda Europeia Sofisticada | Teu Estilo',
                'meta_description' => 'Produtos Zara em Luanda: roupas elegantes, calçados e acessórios com estilo europeu. Qualidade e design contemporâneo. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'H&M',
                'slug' => 'hm',
                'description' => 'Marca sueca de moda sustentável e acessível. Roupas modernas para toda a família com foco em qualidade e preço justo.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Suécia',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 3,
                'meta_title' => 'H&M Angola - Moda Sustentável e Acessível | Teu Estilo',
                'meta_description' => 'H&M em Luanda: roupas modernas, acessórios e moda sustentável. Qualidade sueca a preços acessíveis. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Mango',
                'slug' => 'mango',
                'description' => 'Marca espanhola de moda feminina e masculina. Estilo mediterrâneo contemporâneo com peças versáteis e elegantes.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Espanha',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 4,
                'meta_title' => 'Mango Angola - Estilo Mediterrâneo | Teu Estilo',
                'meta_description' => 'Mango em Luanda: moda feminina e masculina com estilo mediterrâneo. Peças versáteis e elegantes. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Forever 21',
                'slug' => 'forever-21',
                'description' => 'Marca americana de fast fashion jovem e descontraída. Tendências atuais a preços acessíveis para o público jovem.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 5,
                'meta_title' => 'Forever 21 Angola - Moda Jovem | Teu Estilo',
                'meta_description' => 'Forever 21 em Luanda: moda jovem, tendências atuais e estilo descontraído. Preços acessíveis. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Pull & Bear',
                'slug' => 'pull-bear',
                'description' => 'Marca espanhola casual urbana do grupo Inditex. Estilo streetwear moderno e descontraído.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Espanha',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 6,
                'meta_title' => 'Pull & Bear Angola - Streetwear Moderno | Teu Estilo',
                'meta_description' => 'Pull & Bear em Luanda: streetwear urbano, moda casual e estilo jovem. Qualidade espanhola. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ========================================
            // MARCAS DE LUXO (Alta Costura)
            // ========================================
            
            [
                'name' => 'Chanel',
                'slug' => 'chanel',
                'description' => 'Maison francesa de alta costura fundada por Coco Chanel. Sinónimo de elegância, luxo atemporal e sofisticação.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 7,
                'meta_title' => 'Chanel Angola - Alta Costura e Luxo | Teu Estilo',
                'meta_description' => 'Produtos Chanel em Luanda: perfumes icónicos, maquilhagem de luxo e acessórios elegantes. Sofisticação francesa. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Louis Vuitton',
                'slug' => 'louis-vuitton',
                'description' => 'Marca francesa de luxo especializada em malas, acessórios de couro e moda de alta gama. Icónica desde 1854.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 8,
                'meta_title' => 'Louis Vuitton Angola - Luxo Francês | Teu Estilo',
                'meta_description' => 'Louis Vuitton em Luanda: bolsas de luxo, acessórios em couro e moda de alta gama. Elegância francesa desde 1854. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Christian Dior',
                'slug' => 'christian-dior',
                'description' => 'Casa de moda francesa de alta costura. Criadora do New Look, sinónimo de feminilidade, elegância e luxo.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 9,
                'meta_title' => 'Christian Dior Angola - Alta Costura Francesa | Teu Estilo',
                'meta_description' => 'Dior em Luanda: perfumes exclusivos, maquilhagem de luxo e moda de alta costura. Feminilidade e elegância francesa. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Gucci',
                'slug' => 'gucci',
                'description' => 'Marca italiana de luxo conhecida por designs ousados, qualidade artesanal e estilo contemporâneo icónico.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Itália',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 10,
                'meta_title' => 'Gucci Angola - Luxo Italiano Contemporâneo | Teu Estilo',
                'meta_description' => 'Gucci em Luanda: bolsas de luxo, acessórios ousados e moda italiana contemporânea. Estilo icónico. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Versace',
                'slug' => 'versace',
                'description' => 'Casa de moda italiana fundada por Gianni Versace. Conhecida por designs ousados, glamour e luxo extravagante.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Itália',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 11,
                'meta_title' => 'Versace Angola - Glamour Italiano | Teu Estilo',
                'meta_description' => 'Versace em Luanda: moda ousada, perfumes exclusivos e luxo extravagante italiano. Estilo icónico Medusa. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Yves Saint Laurent',
                'slug' => 'ysl',
                'description' => 'Maison francesa de luxo fundada por Yves Saint Laurent. Revolucionou a moda feminina com elegância moderna e ousadia.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 12,
                'meta_title' => 'YSL Angola - Elegância Moderna Francesa | Teu Estilo',
                'meta_description' => 'Yves Saint Laurent em Luanda: maquilhagem de luxo, perfumes icónicos e moda ousada. Elegância francesa revolucionária. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Lacoste',
                'slug' => 'lacoste',
                'description' => 'Marca francesa de moda desportiva elegante. Famosa pelo icónico crocodilo e estilo casual-chic.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 13,
                'meta_title' => 'Lacoste Angola - Moda Desportiva Elegante | Teu Estilo',
                'meta_description' => 'Lacoste em Luanda: polo shirts icónicos, moda casual-chic e estilo desportivo elegante. Qualidade francesa. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Prada',
                'slug' => 'prada',
                'description' => 'Casa de moda italiana de luxo fundada em 1913. Minimalismo sofisticado e qualidade artesanal incomparável.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Itália',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 14,
                'meta_title' => 'Prada Angola - Minimalismo Luxuoso Italiano | Teu Estilo',
                'meta_description' => 'Prada em Luanda: bolsas de luxo, acessórios minimalistas e moda italiana sofisticada. Qualidade desde 1913. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ========================================
            // COSMÉTICOS E BELEZA
            // ========================================
            
            [
                'name' => 'Sephora',
                'slug' => 'sephora',
                'description' => 'Retalhista francesa especializada em cosméticos, skincare e perfumes. Curadoria das melhores marcas de beleza do mundo.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'França',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 15,
                'meta_title' => 'Sephora Angola - Cosméticos e Perfumes | Teu Estilo',
                'meta_description' => 'Produtos Sephora em Luanda: maquilhagem profissional, skincare e perfumes das melhores marcas. Beleza de qualidade. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'MAC Cosmetics',
                'slug' => 'mac',
                'description' => 'Marca canadiana de maquilhagem profissional. Referência mundial em batons, bases e produtos de alta performance.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Canadá',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 16,
                'meta_title' => 'MAC Cosmetics Angola - Maquilhagem Profissional | Teu Estilo',
                'meta_description' => 'MAC em Luanda: batons icónicos, bases de alta cobertura e maquilhagem profissional. Qualidade canadiana. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Carolina Herrera',
                'slug' => 'carolina-herrera',
                'description' => 'Marca venezuelana-americana de moda e perfumes. Elegância clássica, feminilidade e perfumes sofisticados.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Venezuela',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 17,
                'meta_title' => 'Carolina Herrera Angola - Perfumes Sofisticados | Teu Estilo',
                'meta_description' => 'Carolina Herrera em Luanda: perfumes icónicos (Good Girl, 212), moda elegante e feminilidade clássica. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Maybelline',
                'slug' => 'maybelline',
                'description' => 'Marca americana de cosméticos acessíveis. Maquilhagem de qualidade com excelente custo-benefício.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 18,
                'meta_title' => 'Maybelline Angola - Maquilhagem Acessível | Teu Estilo',
                'meta_description' => 'Maybelline em Luanda: máscaras de pestanas, batons e bases a preços acessíveis. Qualidade americana. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'NYX Professional Makeup',
                'slug' => 'nyx',
                'description' => 'Marca americana de maquilhagem profissional acessível. Ampla gama de cores e alta pigmentação.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 19,
                'meta_title' => 'NYX Angola - Maquilhagem Profissional Acessível | Teu Estilo',
                'meta_description' => 'NYX em Luanda: paletas de sombras, batons líquidos e maquilhagem profissional. Preços acessíveis. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'The Ordinary',
                'slug' => 'the-ordinary',
                'description' => 'Marca canadiana de skincare científico e minimalista. Ingredientes de alta qualidade a preços honestos.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Canadá',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 20,
                'meta_title' => 'The Ordinary Angola - Skincare Científico | Teu Estilo',
                'meta_description' => 'The Ordinary em Luanda: séruns, ácidos e skincare científico minimalista. Qualidade a preços honestos. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'CeraVe',
                'slug' => 'cerave',
                'description' => 'Marca americana de cuidados com a pele recomendada por dermatologistas. Fórmulas suaves e eficazes.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 21,
                'meta_title' => 'CeraVe Angola - Skincare Dermatológico | Teu Estilo',
                'meta_description' => 'CeraVe em Luanda: hidratantes, limpadores e cuidados faciais recomendados por dermatologistas. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ========================================
            // PERUCAS E PRODUTOS CAPILARES
            // ========================================
            
            [
                'name' => 'Outre',
                'slug' => 'outre',
                'description' => 'Marca americana líder em perucas sintéticas e naturais. Qualidade superior e estilos versáteis.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 22,
                'meta_title' => 'Outre Angola - Perucas de Qualidade | Teu Estilo',
                'meta_description' => 'Perucas Outre em Luanda: lace fronts, full lace e cabelo sintético de qualidade. Estilos versáteis. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Sensationnel',
                'slug' => 'sensationnel',
                'description' => 'Marca americana especializada em perucas naturais e sintéticas premium. Texturas afro e lisas de alta qualidade.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 23,
                'meta_title' => 'Sensationnel Angola - Perucas Premium | Teu Estilo',
                'meta_description' => 'Perucas Sensationnel em Luanda: cabelo brasileiro, peruano e texturas afro premium. Qualidade profissional. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'FreeTress',
                'slug' => 'freetress',
                'description' => 'Marca de perucas sintéticas acessíveis e estilosas. Excelente custo-benefício e variedade de estilos.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 24,
                'meta_title' => 'FreeTress Angola - Perucas Acessíveis | Teu Estilo',
                'meta_description' => 'Perucas FreeTress em Luanda: sintéticos de qualidade, tranças e crochet braids. Preços acessíveis. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Cantu',
                'slug' => 'cantu',
                'description' => 'Marca americana especializada em produtos para cabelos crespos e cacheados. Fórmulas naturais com manteiga de karité.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 25,
                'meta_title' => 'Cantu Angola - Produtos Cabelo Crespo | Teu Estilo',
                'meta_description' => 'Cantu em Luanda: produtos para cabelo crespo e cacheado, óleos naturais e manteiga de karité. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Shea Moisture',
                'slug' => 'shea-moisture',
                'description' => 'Marca americana de cuidados capilares naturais. Especializada em cabelos afro, crespos e cacheados.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 26,
                'meta_title' => 'Shea Moisture Angola - Cuidados Naturais | Teu Estilo',
                'meta_description' => 'Shea Moisture em Luanda: champôs, condicionadores e máscaras para cabelos afro. Ingredientes naturais. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ========================================
            // ACESSÓRIOS E JOALHERIA
            // ========================================
            
            [
                'name' => 'Pandora',
                'slug' => 'pandora',
                'description' => 'Marca dinamarquesa de joalheria moderna. Famosa pelas pulseiras personalizáveis e charms.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Dinamarca',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 27,
                'meta_title' => 'Pandora Angola - Jóias Personalizáveis | Teu Estilo',
                'meta_description' => 'Pandora em Luanda: pulseiras, charms, brincos e colares em prata. Jóias personalizáveis dinamarquesas. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Swarovski',
                'slug' => 'swarovski',
                'description' => 'Marca austríaca de cristais e joalheria de luxo. Brilho e qualidade inigualáveis desde 1895.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Áustria',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 28,
                'meta_title' => 'Swarovski Angola - Cristais de Luxo | Teu Estilo',
                'meta_description' => 'Swarovski em Luanda: colares, brincos e pulseiras com cristais austríacos. Brilho e elegância desde 1895. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Michael Kors',
                'slug' => 'michael-kors',
                'description' => 'Marca americana de luxo acessível. Bolsas, relógios e acessórios com estilo sofisticado contemporâneo.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 29,
                'meta_title' => 'Michael Kors Angola - Luxo Acessível | Teu Estilo',
                'meta_description' => 'Michael Kors em Luanda: bolsas de luxo, relógios elegantes e acessórios sofisticados. Estilo americano contemporâneo. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // ========================================
            // PLATAFORMAS ONLINE E GENÉRICO
            // ========================================
            
            [
                'name' => 'AliExpress',
                'slug' => 'aliexpress',
                'description' => 'Plataforma chinesa de comércio eletrónico. Variedade imensa de produtos a preços altamente competitivos.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'China',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 30,
                'meta_title' => 'AliExpress Angola - Variedade Online | Teu Estilo',
                'meta_description' => 'Produtos AliExpress em Luanda: roupas, acessórios, cosméticos e eletrónicos. Variedade e preços competitivos. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Lilás',
                'slug' => 'lilas',
                'description' => 'Marca angolana local de moda feminina. Designs exclusivos adaptados ao clima e estilo de Angola.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Angola',
                'is_active' => true,
                'is_featured' => true,
                'display_order' => 31,
                'meta_title' => 'Lilás Angola - Moda Angolana Local | Teu Estilo',
                'meta_description' => 'Lilás: marca angolana de moda feminina em Luanda. Designs exclusivos adaptados ao clima e cultura de Angola. Compre local!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Tiffany & Co.',
                'slug' => 'tiffany',
                'description' => 'Casa joalheira americana icónica fundada em 1837. Jóias de luxo em ouro, platina e diamantes.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 32,
                'meta_title' => 'Tiffany & Co. Angola - Joalheria de Luxo | Teu Estilo',
                'meta_description' => 'Tiffany em Luanda: anéis, colares e pulseiras em ouro e diamantes. Luxo joalheiro americano desde 1837. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Nike',
                'slug' => 'nike',
                'description' => 'Marca americana líder em moda desportiva. Ténis, roupas e acessórios de performance e lifestyle.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Estados Unidos',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 33,
                'meta_title' => 'Nike Angola - Moda Desportiva | Teu Estilo',
                'meta_description' => 'Nike em Luanda: ténis icónicos, roupa desportiva e acessórios de performance. Qualidade americana. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Adidas',
                'slug' => 'adidas',
                'description' => 'Marca alemã de moda desportiva e lifestyle. Performance, conforto e estilo streetwear contemporâneo.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => 'Alemanha',
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 34,
                'meta_title' => 'Adidas Angola - Performance e Estilo | Teu Estilo',
                'meta_description' => 'Adidas em Luanda: ténis, fatos de treino e roupa desportiva. Performance alemã e streetwear moderno. Compre já!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            [
                'name' => 'Genérico',
                'slug' => 'generico',
                'description' => 'Produtos sem marca específica ou marca branca. Opções acessíveis de qualidade sem selo de marca.',
                'logo_path' => null,
                'banner_path' => null,
                'country_origin' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 35,
                'meta_title' => 'Produtos Genéricos Angola - Sem Marca | Teu Estilo',
                'meta_description' => 'Produtos genéricos em Luanda: roupas, acessórios e cosméticos sem marca a preços acessíveis. Qualidade e economia. Compre online!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
        ]);

        $this->command->info('✅ Brands seeded: 35 brands (10 featured) covering fashion, cosmetics, hair, accessories');
            }
}
