<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $suppliers = [
            [
                 'name' => 'Eco Fashion (Outlet & Fardo)',
                'company_name' => 'Ckeuta-Vendas',
                'sku_code' => 'CKEU',
                'tax_id' => null,
                'email' => null,
                'phone' => '929839776',
                'whatsapp' => '929839776',
                'address' => 'Samba - Antigo Control',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Esmeralda Basquete',
                'company_name' => 'Tchiva\'s Shop',
                'sku_code' => 'TCHI',
                'tax_id' => null,
                'email' => null,
                'phone' => '931251840',
                'whatsapp' => '931251840',
                'address' => 'Futungo; Morro Bento',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Tendência MBM',
                'company_name' => 'Tendência MBM',
                'sku_code' => 'TEND',
                'tax_id' => null,
                'email' => null,
                'phone' => '925792097',
                'whatsapp' => '925792097',
                'address' => 'Morro Bento - Antes da paragem da Imetro',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Rebeca Luísa',
                'company_name' => 'Rebeca Luísa',
                'sku_code' => 'REBE',
                'tax_id' => null,
                'email' => null,
                'phone' => '931896810',
                'whatsapp' => '927098724',
                'address' => 'Maculusso - Rua Rei Katyavala',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Sú Pedro',
                'company_name' => 'Sú Pedro',
                'sku_code' => 'SUPE',
                'tax_id' => null,
                'email' => null,
                'phone' => '931584005',
                'whatsapp' => '931584005',
                'address' => 'Viana - Luanda Sul',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Bazar da Allina',
                'company_name' => 'Bazar da Allina',
                'sku_code' => 'ALLI',
                'tax_id' => null,
                'email' => null,
                'phone' => '949780391',
                'whatsapp' => '949780391',
                'address' => 'Kimbango - Estrada novo campo',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Bazar da Ira',
                'company_name' => 'Bazar da Ira',
                'sku_code' => 'BIRA',
                'tax_id' => null,
                'email' => null,
                'phone' => '955194473',
                'whatsapp' => '938839190',
                'address' => 'Patriota',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Ró Élégance',
                'company_name' => 'Ró Élégance',
                'sku_code' => 'ROEL',
                'tax_id' => null,
                'email' => 'roloja540@gmail.com',
                'phone' => '951770524',
                'whatsapp' => '951770524',
                'address' => 'Prenda',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'AyaBelle',
                'company_name' => 'AyaBelle',
                'sku_code' => 'AYAB',
                'tax_id' => null,
                'email' => null,
                'phone' => '945500020',
                'whatsapp' => '945500020',
                'address' => 'Gamek - Perto do nosso Centro',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Rosa Neide',
                'company_name' => 'Fardo da Rosa',
                'sku_code' => 'ROSA',
                'tax_id' => null,
                'email' => 'rosaneide714@gmail.com',
                'phone' => '922577989',
                'whatsapp' => '922577989',
                'address' => 'Cazenga - Paragem do Hospital dos Cajueiros',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Mille xtylus Boutique',
                'company_name' => 'Mille xtylus Boutique',
                'sku_code' => 'MILL',
                'tax_id' => null,
                'email' => null,
                'phone' => '912408340',
                'whatsapp' => '912408340',
                'address' => 'Camama',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Naita Angola',
                'company_name' => 'Naita Angola',
                'sku_code' => 'NAIT',
                'tax_id' => null,
                'email' => null,
                'phone' => '940276604',
                'whatsapp' => '972351199',
                'address' => 'Camama 1 - Rua do Banco Atlântico',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Marcia Saluvo',
                'company_name' => 'Marcia Saluvo',
                'sku_code' => 'MARC',
                'tax_id' => null,
                'email' => null,
                'phone' => '900000001', // Placeholder - sem telefone
                'whatsapp' => null,
                'address' => 'Sequele',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => 'Sem telefone registado',
            ],
            [
                'name' => 'Rossana Pedro',
                'company_name' => 'Rossana Pedro',
                'sku_code' => 'ROSS',
                'tax_id' => null,
                'email' => null,
                'phone' => '943148829',
                'whatsapp' => '943148829',
                'address' => 'Zango',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Encantos da Jó',
                'company_name' => 'Encantos da Jó',
                'sku_code' => 'ENJO',
                'tax_id' => null,
                'email' => 'jornezajoao@gmail.com',
                'phone' => '944503494',
                'whatsapp' => '944503494',
                'address' => 'Vila de Viana',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Hello Mulheres',
                'company_name' => 'Hello Mulheres',
                'sku_code' => 'HELL',
                'tax_id' => null,
                'email' => null,
                'phone' => '972594060',
                'whatsapp' => '972594060',
                'address' => 'Viana - Grafanil Bar',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Teresa Rodrigues',
                'company_name' => 'Teresa Rodrigues',
                'sku_code' => 'TERE',
                'tax_id' => null,
                'email' => null,
                'phone' => '932033852',
                'whatsapp' => '932033852',
                'address' => 'Ilha de Luanda',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Império Feminino',
                'company_name' => 'Império Feminino',
                'sku_code' => 'IMPE',
                'tax_id' => null,
                'email' => null,
                'phone' => '945276266',
                'whatsapp' => '945276266',
                'address' => null,
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Sita\'s Closet',
                'company_name' => 'Sita\'s Closet',
                'sku_code' => 'SITA',
                'tax_id' => null,
                'email' => null,
                'phone' => '949406884',
                'whatsapp' => '949406884',
                'address' => 'Camama 1 - Casa Prelex',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
            ],
            [
                'name' => 'Núria Iracelma',
                'company_name' => 'Teu Estilo',
                'sku_code' => 'TEST',
                'tax_id' => null,
                'email' => null,
                'phone' => '928496036',
                'whatsapp' => '928496036',
                'address' => 'Kikagil',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'cash',
                'payment_terms_notes' => 'Estoque próprio da Teu Estilo',
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => false, // ESTOQUE PRÓPRIO
                'commission_percentage' => null,
                'rating' => 5,
                'notes' => 'Fornecedor interno - estoque próprio da Teu Estilo',
            ],
        ];

        foreach ($suppliers as $supplier) {
            DB::table('suppliers')->updateOrInsert(
                ['phone' => $supplier['phone']], // Chave única (telefone)
                [
                    'name' => $supplier['name'],
                    'company_name' => $supplier['company_name'],
                    'sku_code' => $supplier['sku_code'],
                    'tax_id' => $supplier['tax_id'],
                    'email' => $supplier['email'],
                    'whatsapp' => $supplier['whatsapp'],
                    'address' => $supplier['address'],
                    'city' => $supplier['city'],
                    'province' => $supplier['province'],
                    'country' => $supplier['country'],
                    'payment_terms' => $supplier['payment_terms'],
                    'payment_terms_notes' => $supplier['payment_terms_notes'],
                    'credit_limit' => $supplier['credit_limit'],
                    'bank_name' => $supplier['bank_name'],
                    'bank_account' => $supplier['bank_account'],
                    'iban' => $supplier['iban'],
                    'is_active' => $supplier['is_active'],
                    'is_consignment' => $supplier['is_consignment'],
                    'commission_percentage' => $supplier['commission_percentage'],
                    'rating' => $supplier['rating'],
                    'notes' => $supplier['notes'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }

        $this->command->info('✅ Suppliers seeded: 20 suppliers with SKU codes (19 consignment + 1 own stock)');
    }
}