<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('suppliers')->insert([
            
            // 1. Eco Fashion (Outlet & Fardo)
            [
                'name' => 'Eco Fashion (Outlet & Fardo)',
                'company_name' => 'Ckeuta-Vendas',
                'tax_id' => null,
                'email' => null,
                'phone' => '929 839 776',
                'whatsapp' => '929 839 776',
                'address' => 'Samba - Antigo Control',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 2. Esmeralda Basquete
            [
                'name' => 'Esmeralda Basquete',
                'company_name' => 'Tchiva\'s Shop',
                'tax_id' => null,
                'email' => null,
                'phone' => '931251840',
                'whatsapp' => '931251840',
                'address' => 'Futungo; Morro Bento',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 3. Tendência MBM
            [
                'name' => 'Tendência MBM',
                'company_name' => 'Tendência MBM',
                'tax_id' => null,
                'email' => null,
                'phone' => '925 792 097',
                'whatsapp' => '925 792 097',
                'address' => 'Morro Bento - Antes da paragem da Imetro (sentido)',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 4. Rebeca Luísa
            [
                'name' => 'Rebeca Luísa',
                'company_name' => 'Rebeca Luísa',
                'tax_id' => null,
                'email' => null,
                'phone' => '931896810',
                'whatsapp' => '927098724',
                'address' => 'Maculusso - Rua Rei Katyavala',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 5. Sú Pedro
            [
                'name' => 'Sú Pedro',
                'company_name' => 'Sú Pedro',
                'tax_id' => null,
                'email' => null,
                'phone' => '931 584 005',
                'whatsapp' => '931 584 005',
                'address' => 'Viana - Luanda Sul',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 6. Bazar da Allina
            [
                'name' => 'Bazar da Allina',
                'company_name' => 'Bazar da Allina',
                'tax_id' => null,
                'email' => null,
                'phone' => '949780391',
                'whatsapp' => '949780391',
                'address' => 'Kimbango - Estrada novo campo',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 7. Bazar da Ira
            [
                'name' => 'Bazar da Ira',
                'company_name' => 'Bazar da Ira',
                'tax_id' => null,
                'email' => null,
                'phone' => '955 194 473',
                'whatsapp' => '938 839 190',
                'address' => 'Patriota',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 8. Ró Élégance
            [
                'name' => 'Ró Élégance',
                'company_name' => 'Ró Élégance',
                'tax_id' => null,
                'email' => 'roloja540@gmail.com',
                'phone' => '951770524',
                'whatsapp' => '951770524',
                'address' => 'Prenda',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 9. AyaBelle
            [
                'name' => 'AyaBelle',
                'company_name' => 'AyaBelle',
                'tax_id' => null,
                'email' => null,
                'phone' => '945 500 020',
                'whatsapp' => '945 500 020',
                'address' => 'Gamek - Perto do nosso Centro',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 10. Rosa Neide Fardo da Rosa
            [
                'name' => 'Rosa Neide',
                'company_name' => 'Fardo da Rosa',
                'tax_id' => null,
                'email' => 'rosaneide714@gmail.com',
                'phone' => '922577989',
                'whatsapp' => '922577989',
                'address' => 'Cazenga - Paragem do Hospital dos Cajueiros',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 11. Mille xtylus Boutique
            [
                'name' => 'Mille xtylus Boutique',
                'company_name' => 'Mille xtylus Boutique',
                'tax_id' => null,
                'email' => null,
                'phone' => '912408340',
                'whatsapp' => '912 408 340',
                'address' => 'Camama',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 12. Naita Angola
            [
                'name' => 'Naita Angola',
                'company_name' => 'Naita Angola',
                'tax_id' => null,
                'email' => null,
                'phone' => '940276604',
                'whatsapp' => '972351199',
                'address' => 'Camama 1 - Rua do Banco Atlântico (cidade universitária)',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 13. Marcia Saluvo
            [
                'name' => 'Marcia Saluvo',
                'company_name' => 'Marcia Saluvo',
                'tax_id' => null,
                'email' => null,
                'phone' => null,
                'whatsapp' => null,
                'address' => 'Sequele',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 14. Rossana Pedro
            [
                'name' => 'Rossana Pedro',
                'company_name' => 'Rossana Pedro',
                'tax_id' => null,
                'email' => null,
                'phone' => '943148829',
                'whatsapp' => '943148829',
                'address' => 'Zango',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 15. Encantos da Jó
            [
                'name' => 'Encantos da Jó',
                'company_name' => 'Encantos da Jó',
                'tax_id' => null,
                'email' => 'jornezajoao@gmail.com',
                'phone' => '944503494',
                'whatsapp' => '944503494',
                'address' => 'Vila de Viana',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 16. Hello Mulheres
            [
                'name' => 'Hello Mulheres',
                'company_name' => 'Hello Mulheres',
                'tax_id' => null,
                'email' => null,
                'phone' => '972594060',
                'whatsapp' => '972594060',
                'address' => 'Viana - Grafanil Bar',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 17. Teresa Rodrigues
            [
                'name' => 'Teresa Rodrigues',
                'company_name' => 'Teresa Rodrigues',
                'tax_id' => null,
                'email' => null,
                'phone' => '932033852',
                'whatsapp' => '932033852',
                'address' => 'Ilha de Luanda',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 18. Império Feminino
            [
                'name' => 'Império Feminino',
                'company_name' => 'Império Feminino',
                'tax_id' => null,
                'email' => null,
                'phone' => '945276266',
                'whatsapp' => '945276266',
                'address' => null,
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 19. Sita's Closet
            [
                'name' => 'Sita\'s Closet',
                'company_name' => 'Sita\'s Closet',
                'tax_id' => null,
                'email' => null,
                'phone' => '949406884',
                'whatsapp' => '949406884',
                'address' => 'Camama 1 - Casa Prelex',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'custom',
                'payment_terms_notes' => null,
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => true,
                'commission_percentage' => null,
                'rating' => null,
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // 20. Núria Iracelma - TEU ESTILO (ESTOQUE PRÓPRIO!)
            [
                'name' => 'Núria Iracelma',
                'company_name' => 'Teu Estilo',
                'tax_id' => null,
                'email' => null,
                'phone' => '928496036',
                'whatsapp' => '928496036',
                'address' => 'Kikagil',
                'city' => 'Luanda',
                'province' => 'Luanda',
                'country' => 'Angola',
                'payment_terms' => 'cash',  // ⬅️ Próprio = pagamento à vista
                'payment_terms_notes' => 'Estoque próprio da Teu Estilo',
                'credit_limit' => null,
                'bank_name' => null,
                'bank_account' => null,
                'iban' => null,
                'is_active' => true,
                'is_consignment' => false,  // ⬅️ FALSE = ESTOQUE PRÓPRIO!
                'commission_percentage' => null,  // ⬅️ Não tem comissão (é teu!)
                'rating' => 5,  // ⬅️ 5 estrelas (é a tua loja!)
                'notes' => 'Fornecedor interno - estoque próprio da Teu Estilo',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
        ]);

        $this->command->info('✅ Suppliers seeded: 20 suppliers (19 consignment + 1 own stock - Teu Estilo)');
    }
}
